'use strict';

const path = require('path');
const fs = require('fs-extra');
const os = require('os');

/**
 * Manages FTC project creation, configuration, and lifecycle.
 * Creates new Gradle+Android projects with FTC SDK and optional libraries.
 */
class ProjectManager {
  constructor() {
    this.templateDir = path.join(__dirname, '../../ftc-project');
  }

  /**
   * Create a new FTC project.
   * @param {object} options - { name, basePath, packageName, libs }
   * @param {function} progressCallback
   */
  async createProject(options, progressCallback) {
    const { name, basePath, packageName = 'org.firstinspires.ftc.teamcode', libs = {} } = options;
    const projectPath = path.join(basePath, name);

    progressCallback && progressCallback(`Creating project directory: ${projectPath}`);
    await fs.ensureDir(projectPath);

    // Copy the template FTC project
    if (await fs.pathExists(this.templateDir)) {
      progressCallback && progressCallback('Copying FTC project template...');
      await fs.copy(this.templateDir, projectPath, { overwrite: false });
    } else {
      progressCallback && progressCallback('Generating project structure...');
      await this._generateProjectStructure(projectPath, name, packageName, libs);
    }

    // Create TeamCode source directory
    const srcDir = path.join(projectPath, 'TeamCode', 'src', 'main', 'java',
      ...packageName.split('.'));
    await fs.ensureDir(srcDir);
    await fs.writeFile(path.join(srcDir, '.gitkeep'), '');

    // Customize build.gradle with selected libs
    await this._customizeBuildGradle(projectPath, libs);

    // Create .gitignore
    await this._createGitignore(projectPath);

    // Create local.properties (placeholder)
    await fs.writeFile(path.join(projectPath, 'local.properties'),
      `# Generated by FTC IDE\nsdk.dir=/path/to/android/sdk\n`);

    progressCallback && progressCallback(`Project "${name}" created successfully!`);
    return { success: true, path: projectPath, name };
  }

  async openProject(projectPath) {
    const exists = await fs.pathExists(projectPath);
    if (!exists) throw new Error(`Path not found: ${projectPath}`);

    const info = await this.getProjectInfo(projectPath);
    return { success: true, ...info };
  }

  async getProjectInfo(projectPath) {
    const settingsGradle = path.join(projectPath, 'settings.gradle');
    const rootBuildGradle = path.join(projectPath, 'build.gradle');
    const teamCodeGradle = path.join(projectPath, 'TeamCode', 'build.gradle');

    const info = { path: projectPath, name: path.basename(projectPath), type: 'unknown' };

    if (await fs.pathExists(settingsGradle)) {
      info.type = 'android-gradle';
      try {
        const settings = await fs.readFile(settingsGradle, 'utf8');
        info.modules = (settings.match(/include\s+['"]:([^'"]+)['"]/g) || [])
          .map(m => m.replace(/include\s+['"]:/, '').replace(/['"]/g, ''));
      } catch (e) {}
    }

    return info;
  }

  /** Copy the ftc-project template to a destination */
  async copyFtcTemplate(destPath) {
    if (!await fs.pathExists(this.templateDir)) {
      throw new Error('FTC template not found');
    }
    await fs.copy(this.templateDir, destPath);
    return { success: true };
  }

  async _generateProjectStructure(projectPath, name, packageName, libs) {
    const dirs = [
      'TeamCode/src/main/java',
      'TeamCode/src/main/res',
      'FtcRobotController/src/main/java',
      'gradle/wrapper'
    ];
    for (const d of dirs) await fs.ensureDir(path.join(projectPath, d));

    // settings.gradle
    await fs.writeFile(path.join(projectPath, 'settings.gradle'),
      `include ':TeamCode', ':FtcRobotController'\n`);

    // Root build.gradle
    await fs.writeFile(path.join(projectPath, 'build.gradle'),
      this._rootBuildGradleContent());

    // TeamCode build.gradle
    await fs.writeFile(path.join(projectPath, 'TeamCode', 'build.gradle'),
      this._teamCodeBuildGradleContent(libs));

    // FtcRobotController build.gradle
    await fs.writeFile(path.join(projectPath, 'FtcRobotController', 'build.gradle'),
      this._ftcRobotControllerGradleContent());

    // Gradle wrapper
    await fs.writeFile(path.join(projectPath, 'gradle', 'wrapper', 'gradle-wrapper.properties'),
      this._gradleWrapperProperties());

    // gradlew scripts (minimal stubs – real ones should be from SDK)
    await fs.writeFile(path.join(projectPath, 'gradlew'), this._gradlewScript(), { mode: 0o755 });
    await fs.writeFile(path.join(projectPath, 'gradlew.bat'), this._gradlewBatScript());

    // gradle.properties (Sloth Mode speed optimizations)
    await fs.writeFile(path.join(projectPath, 'gradle.properties'), this._gradleProperties());
  }

  async _customizeBuildGradle(projectPath, libs) {
    const gradlePath = path.join(projectPath, 'TeamCode', 'build.gradle');
    if (!await fs.pathExists(gradlePath)) return;

    let content = await fs.readFile(gradlePath, 'utf8');

    if (!libs.pedro) {
      content = content.replace(/.*PedroPathing.*\n/g, '');
    }
    if (!libs.nextftc) {
      content = content.replace(/.*nextftc.*\n/g, '');
    }
    if (!libs.dashboard) {
      content = content.replace(/.*ftc-dashboard.*\n/g, '');
    }
    if (libs.roadrunner && !content.includes('roadrunner')) {
      content = content.replace(
        '// Road Runner (optional)',
        "implementation 'com.acmerobotics.roadrunner:core:1.0.0'"
      );
    }

    await fs.writeFile(gradlePath, content);
  }

  async _createGitignore(projectPath) {
    const content = `# Android/Gradle
.gradle/
build/
local.properties
*.keystore
*.iml

# IDE
.idea/
*.class

# Node (for FTC IDE)
node_modules/

# OS
.DS_Store
Thumbs.db
`;
    await fs.writeFile(path.join(projectPath, '.gitignore'), content);
  }

  _rootBuildGradleContent() {
    return `// Top-level build file
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.brott.dev/' }
        maven { url 'https://jitpack.io' }
        maven { url 'https://mvnrepository.com/artifact/' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`;
  }

  _teamCodeBuildGradleContent(libs = {}) {
    return `apply plugin: 'com.android.application'

android {
    compileSdkVersion 33
    defaultConfig {
        applicationId "com.qualcomm.ftcrobotcontroller"
        minSdkVersion 24
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release { minifyEnabled false }
        debug { debuggable true }
    }
    namespace 'org.firstinspires.ftc.teamcode'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation project(':FtcRobotController')

    // PedroPathing – developer branch
    ${libs.pedro !== false ? "implementation 'com.github.Pedro-Pathing:PedroPathing:developer-SNAPSHOT'" : '// PedroPathing disabled'}

    // NextFTC
    ${libs.nextftc !== false ? "implementation 'com.github.rowan-mcalpin:nextftc:main-SNAPSHOT'" : '// NextFTC disabled'}

    // FTC Dashboard
    ${libs.dashboard !== false ? "releaseImplementation 'com.acmerobotics.dashboard:dashboard:0.4.16'\n    debugImplementation 'com.acmerobotics.dashboard:dashboard:0.4.16'" : '// FTC Dashboard disabled'}

    // Road Runner (optional)
    // implementation 'com.acmerobotics.roadrunner:core:1.0.0'
}
`;
  }

  _ftcRobotControllerGradleContent() {
    return `apply plugin: 'com.android.library'

android {
    compileSdkVersion 33
    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 33
    }
    namespace 'com.qualcomm.ftcrobotcontroller'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'org.firstinspires.ftc:RobotCore:9.0.1'
    implementation 'org.firstinspires.ftc:RobotServer:9.0.1'
    implementation 'org.firstinspires.ftc:OnBotJava:9.0.1'
    implementation 'org.firstinspires.ftc:Hardware:9.0.1'
    implementation 'org.firstinspires.ftc:FtcCommon:9.0.1'
    implementation 'org.firstinspires.ftc:Vision:9.0.1'
}
`;
  }

  _gradleWrapperProperties() {
    return `distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-8.1.1-bin.zip
`;
  }

  _gradlewScript() {
    return `#!/bin/sh
##############################################################################
# Gradle start up script for UN*X
##############################################################################
exec "$(dirname "$0")/gradle/wrapper/gradle-wrapper.jar" "$@"
`;
  }

  _gradlewBatScript() {
    return `@echo off
setlocal
set DIRNAME=%~dp0
call "%DIRNAME%gradle\\wrapper\\gradlew.bat" %*
`;
  }

  _gradleProperties() {
    return `# ─── Sloth Mode: Gradle Performance Optimizations ───
# These settings significantly speed up builds on FTC Control Hub projects.

# Keep the Gradle daemon running between builds to avoid JVM startup overhead.
org.gradle.daemon=true

# Build independent modules in parallel.
org.gradle.parallel=true

# Enable the Gradle build cache to reuse outputs from previous builds.
org.gradle.caching=true

# Only configure modules that are needed for the requested tasks.
org.gradle.configureondemand=true

# Allocate more memory to the Gradle JVM for faster compilation.
org.gradle.jvmargs=-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Use AndroidX libraries.
android.useAndroidX=true
`;
  }
}

module.exports = ProjectManager;
